package com.creatshare.answerapi.pojo;

import java.util.ArrayList;
import java.util.List;

public class QuestionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public QuestionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuIdIsNull() {
            addCriterion("qu_id is null");
            return (Criteria) this;
        }

        public Criteria andQuIdIsNotNull() {
            addCriterion("qu_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuIdEqualTo(Integer value) {
            addCriterion("qu_id =", value, "quId");
            return (Criteria) this;
        }

        public Criteria andQuIdNotEqualTo(Integer value) {
            addCriterion("qu_id <>", value, "quId");
            return (Criteria) this;
        }

        public Criteria andQuIdGreaterThan(Integer value) {
            addCriterion("qu_id >", value, "quId");
            return (Criteria) this;
        }

        public Criteria andQuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("qu_id >=", value, "quId");
            return (Criteria) this;
        }

        public Criteria andQuIdLessThan(Integer value) {
            addCriterion("qu_id <", value, "quId");
            return (Criteria) this;
        }

        public Criteria andQuIdLessThanOrEqualTo(Integer value) {
            addCriterion("qu_id <=", value, "quId");
            return (Criteria) this;
        }

        public Criteria andQuIdIn(List<Integer> values) {
            addCriterion("qu_id in", values, "quId");
            return (Criteria) this;
        }

        public Criteria andQuIdNotIn(List<Integer> values) {
            addCriterion("qu_id not in", values, "quId");
            return (Criteria) this;
        }

        public Criteria andQuIdBetween(Integer value1, Integer value2) {
            addCriterion("qu_id between", value1, value2, "quId");
            return (Criteria) this;
        }

        public Criteria andQuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("qu_id not between", value1, value2, "quId");
            return (Criteria) this;
        }

        public Criteria andQuTypeIsNull() {
            addCriterion("qu_type is null");
            return (Criteria) this;
        }

        public Criteria andQuTypeIsNotNull() {
            addCriterion("qu_type is not null");
            return (Criteria) this;
        }

        public Criteria andQuTypeEqualTo(Integer value) {
            addCriterion("qu_type =", value, "quType");
            return (Criteria) this;
        }

        public Criteria andQuTypeNotEqualTo(Integer value) {
            addCriterion("qu_type <>", value, "quType");
            return (Criteria) this;
        }

        public Criteria andQuTypeGreaterThan(Integer value) {
            addCriterion("qu_type >", value, "quType");
            return (Criteria) this;
        }

        public Criteria andQuTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("qu_type >=", value, "quType");
            return (Criteria) this;
        }

        public Criteria andQuTypeLessThan(Integer value) {
            addCriterion("qu_type <", value, "quType");
            return (Criteria) this;
        }

        public Criteria andQuTypeLessThanOrEqualTo(Integer value) {
            addCriterion("qu_type <=", value, "quType");
            return (Criteria) this;
        }

        public Criteria andQuTypeIn(List<Integer> values) {
            addCriterion("qu_type in", values, "quType");
            return (Criteria) this;
        }

        public Criteria andQuTypeNotIn(List<Integer> values) {
            addCriterion("qu_type not in", values, "quType");
            return (Criteria) this;
        }

        public Criteria andQuTypeBetween(Integer value1, Integer value2) {
            addCriterion("qu_type between", value1, value2, "quType");
            return (Criteria) this;
        }

        public Criteria andQuTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("qu_type not between", value1, value2, "quType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}