package com.creatshare.answerapi.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;

import javax.validation.constraints.*;
import java.io.Serializable;
import java.math.BigDecimal;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class UserInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_num
     *
     * @mbg.generated
     */
    @Size(min = 8,max = 8,message = "学号必须八位")
    private String userNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated
     */
    @Size(min = 1,max = 5,message = "姓名过长")
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_direction
     *
     * @mbg.generated
     */
    @NotBlank(message = "方向不能为空")
    private String userDirection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_choice
     *
     * @mbg.generated
     */
    @NotNull(message = "选择题正确个数不能为空")
    private Integer userChoice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_program
     *
     * @mbg.generated
     */
    @NotNull(message = "编程题通过率不能为空")
    private BigDecimal userProgram;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_result
     *
     * @mbg.generated
     */
    @NotNull(message = "状态不能为空")
    private Integer userResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_answer
     *
     * @mbg.generated
     */
    @NotBlank(message = "答案不能为空")
    private String userAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_num
     *
     * @return the value of user_info.user_num
     *
     * @mbg.generated
     */
    public String getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_num
     *
     * @param userNum the value for user_info.user_num
     *
     * @mbg.generated
     */
    public void setUserNum(String userNum) {
        this.userNum = userNum == null ? null : userNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_direction
     *
     * @return the value of user_info.user_direction
     *
     * @mbg.generated
     */
    public String getUserDirection() {
        return userDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_direction
     *
     * @param userDirection the value for user_info.user_direction
     *
     * @mbg.generated
     */
    public void setUserDirection(String userDirection) {
        this.userDirection = userDirection == null ? null : userDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_choice
     *
     * @return the value of user_info.user_choice
     *
     * @mbg.generated
     */
    public Integer getUserChoice() {
        return userChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_choice
     *
     * @param userChoice the value for user_info.user_choice
     *
     * @mbg.generated
     */
    public void setUserChoice(Integer userChoice) {
        this.userChoice = userChoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_program
     *
     * @return the value of user_info.user_program
     *
     * @mbg.generated
     */
    public BigDecimal getUserProgram() {
        return userProgram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_program
     *
     * @param userProgram the value for user_info.user_program
     *
     * @mbg.generated
     */
    public void setUserProgram(BigDecimal userProgram) {
        this.userProgram = userProgram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_result
     *
     * @return the value of user_info.user_result
     *
     * @mbg.generated
     */
    public Integer getUserResult() {
        return userResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_result
     *
     * @param userResult the value for user_info.user_result
     *
     * @mbg.generated
     */
    public void setUserResult(Integer userResult) {
        this.userResult = userResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_answer
     *
     * @return the value of user_info.user_answer
     *
     * @mbg.generated
     */
    public String getUserAnswer() {
        return userAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_answer
     *
     * @param userAnswer the value for user_info.user_answer
     *
     * @mbg.generated
     */
    public void setUserAnswer(String userAnswer) {
        this.userAnswer = userAnswer == null ? null : userAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", userNum=").append(userNum);
        sb.append(", userName=").append(userName);
        sb.append(", userDirection=").append(userDirection);
        sb.append(", userChoice=").append(userChoice);
        sb.append(", userProgram=").append(userProgram);
        sb.append(", userResult=").append(userResult);
        sb.append(", userAnswer=").append(userAnswer);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}