package com.creatshare.answerapi.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNumIsNull() {
            addCriterion("user_num is null");
            return (Criteria) this;
        }

        public Criteria andUserNumIsNotNull() {
            addCriterion("user_num is not null");
            return (Criteria) this;
        }

        public Criteria andUserNumEqualTo(String value) {
            addCriterion("user_num =", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotEqualTo(String value) {
            addCriterion("user_num <>", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumGreaterThan(String value) {
            addCriterion("user_num >", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumGreaterThanOrEqualTo(String value) {
            addCriterion("user_num >=", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLessThan(String value) {
            addCriterion("user_num <", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLessThanOrEqualTo(String value) {
            addCriterion("user_num <=", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumLike(String value) {
            addCriterion("user_num like", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotLike(String value) {
            addCriterion("user_num not like", value, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumIn(List<String> values) {
            addCriterion("user_num in", values, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotIn(List<String> values) {
            addCriterion("user_num not in", values, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumBetween(String value1, String value2) {
            addCriterion("user_num between", value1, value2, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNumNotBetween(String value1, String value2) {
            addCriterion("user_num not between", value1, value2, "userNum");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserDirectionIsNull() {
            addCriterion("user_direction is null");
            return (Criteria) this;
        }

        public Criteria andUserDirectionIsNotNull() {
            addCriterion("user_direction is not null");
            return (Criteria) this;
        }

        public Criteria andUserDirectionEqualTo(String value) {
            addCriterion("user_direction =", value, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionNotEqualTo(String value) {
            addCriterion("user_direction <>", value, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionGreaterThan(String value) {
            addCriterion("user_direction >", value, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("user_direction >=", value, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionLessThan(String value) {
            addCriterion("user_direction <", value, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionLessThanOrEqualTo(String value) {
            addCriterion("user_direction <=", value, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionLike(String value) {
            addCriterion("user_direction like", value, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionNotLike(String value) {
            addCriterion("user_direction not like", value, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionIn(List<String> values) {
            addCriterion("user_direction in", values, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionNotIn(List<String> values) {
            addCriterion("user_direction not in", values, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionBetween(String value1, String value2) {
            addCriterion("user_direction between", value1, value2, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserDirectionNotBetween(String value1, String value2) {
            addCriterion("user_direction not between", value1, value2, "userDirection");
            return (Criteria) this;
        }

        public Criteria andUserChoiceIsNull() {
            addCriterion("user_choice is null");
            return (Criteria) this;
        }

        public Criteria andUserChoiceIsNotNull() {
            addCriterion("user_choice is not null");
            return (Criteria) this;
        }

        public Criteria andUserChoiceEqualTo(Integer value) {
            addCriterion("user_choice =", value, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserChoiceNotEqualTo(Integer value) {
            addCriterion("user_choice <>", value, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserChoiceGreaterThan(Integer value) {
            addCriterion("user_choice >", value, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserChoiceGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_choice >=", value, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserChoiceLessThan(Integer value) {
            addCriterion("user_choice <", value, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserChoiceLessThanOrEqualTo(Integer value) {
            addCriterion("user_choice <=", value, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserChoiceIn(List<Integer> values) {
            addCriterion("user_choice in", values, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserChoiceNotIn(List<Integer> values) {
            addCriterion("user_choice not in", values, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserChoiceBetween(Integer value1, Integer value2) {
            addCriterion("user_choice between", value1, value2, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserChoiceNotBetween(Integer value1, Integer value2) {
            addCriterion("user_choice not between", value1, value2, "userChoice");
            return (Criteria) this;
        }

        public Criteria andUserProgramIsNull() {
            addCriterion("user_program is null");
            return (Criteria) this;
        }

        public Criteria andUserProgramIsNotNull() {
            addCriterion("user_program is not null");
            return (Criteria) this;
        }

        public Criteria andUserProgramEqualTo(BigDecimal value) {
            addCriterion("user_program =", value, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserProgramNotEqualTo(BigDecimal value) {
            addCriterion("user_program <>", value, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserProgramGreaterThan(BigDecimal value) {
            addCriterion("user_program >", value, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserProgramGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("user_program >=", value, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserProgramLessThan(BigDecimal value) {
            addCriterion("user_program <", value, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserProgramLessThanOrEqualTo(BigDecimal value) {
            addCriterion("user_program <=", value, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserProgramIn(List<BigDecimal> values) {
            addCriterion("user_program in", values, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserProgramNotIn(List<BigDecimal> values) {
            addCriterion("user_program not in", values, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserProgramBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("user_program between", value1, value2, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserProgramNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("user_program not between", value1, value2, "userProgram");
            return (Criteria) this;
        }

        public Criteria andUserResultIsNull() {
            addCriterion("user_result is null");
            return (Criteria) this;
        }

        public Criteria andUserResultIsNotNull() {
            addCriterion("user_result is not null");
            return (Criteria) this;
        }

        public Criteria andUserResultEqualTo(Integer value) {
            addCriterion("user_result =", value, "userResult");
            return (Criteria) this;
        }

        public Criteria andUserResultNotEqualTo(Integer value) {
            addCriterion("user_result <>", value, "userResult");
            return (Criteria) this;
        }

        public Criteria andUserResultGreaterThan(Integer value) {
            addCriterion("user_result >", value, "userResult");
            return (Criteria) this;
        }

        public Criteria andUserResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_result >=", value, "userResult");
            return (Criteria) this;
        }

        public Criteria andUserResultLessThan(Integer value) {
            addCriterion("user_result <", value, "userResult");
            return (Criteria) this;
        }

        public Criteria andUserResultLessThanOrEqualTo(Integer value) {
            addCriterion("user_result <=", value, "userResult");
            return (Criteria) this;
        }

        public Criteria andUserResultIn(List<Integer> values) {
            addCriterion("user_result in", values, "userResult");
            return (Criteria) this;
        }

        public Criteria andUserResultNotIn(List<Integer> values) {
            addCriterion("user_result not in", values, "userResult");
            return (Criteria) this;
        }

        public Criteria andUserResultBetween(Integer value1, Integer value2) {
            addCriterion("user_result between", value1, value2, "userResult");
            return (Criteria) this;
        }

        public Criteria andUserResultNotBetween(Integer value1, Integer value2) {
            addCriterion("user_result not between", value1, value2, "userResult");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}